;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        js2-mode-show-node
        ))

(setq mc/cmds-to-run-once
      '(
        ido-find-file
        indent-for-tab-command
        mouse-set-region
        org-self-insert-command
        yaml-electric-backspace
        ))
