;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-semi&comma
        end-of-buffer
        js2-mode-show-node
        org-beginning-of-line
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        comment-dwim
        handle-switch-frame
        ido-find-file
        ido-switch-buffer
        iedit-switch-to-mc-mode
        indent-for-tab-command
        journal
        js2-down-mouse-3
        make-frame
        mouse-drag-secondary
        mouse-save-then-kill
        mouse-set-region
        org-agenda
        org-find-file-at-mouse
        org-open-at-mouse
        org-self-insert-command
        yaml-electric-backspace
        ))
