;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        end-of-buffer
        js2-mode-show-node
        ))

(setq mc/cmds-to-run-once
      '(
        ido-find-file
        ido-switch-buffer
        indent-for-tab-command
        mouse-drag-secondary
        mouse-set-region
        org-find-file-at-mouse
        org-open-at-mouse
        org-self-insert-command
        yaml-electric-backspace
        ))
